### PR TITLE
Set `java.awt.headless` to `true` due to Windows 11 issues

### LINKED ISSUE #311: plantuml-server:jetty-v1.2023.10 Could not initialize class net.sourceforge.plantuml.FileFormat
**Describe the bug**
After starting the plantuml-server docker container, it does not render any scripts to diagrams

**To Reproduce**
```bash
docker pull plantuml/plantuml-server:jetty
docker run --restart unless-stopped -d --name plantuml -p 8082:8080 plantuml/plantuml-server:jetty
```

1. Go to <http://localhost:8082/>
4. See error into frame with diagrams (not rendering). It's true for all formats (png, svg, ascii, pdf)

**Expected behavior**
A rendered diagram into frame. 

**Desktop (please complete the following information):**

- OS: Windows 11 Pro (22H2 / 22621.2134)
- Browser chrome (v 115.0.5790.171), edge (v 115.0.1901.203)
- Docker: Docker Desktop 4.22.0 (117440)

**Additional context**
```bash
docker logs plantuml | grep -i Error
```
```
java.lang.UnsatisfiedLinkError: /opt/java/openjdk/lib/libawt_xawt.so: libXext.so.6: cannot open shared object file: No such file or directory
java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.plantuml.FileFormat
java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.plantuml.FileFormat
```
<details><summary>Detail log</summary>
<p>

```
2023-08-16 22:27:31 2023-08-16 17:27:31.419:WARN :oejs.HttpChannel:qtp1576861390-22: /map/SyfFKj2rKt3CoKnELR1Io4ZDoSbNACyloaa10000
2023-08-16 22:27:31 java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.plantuml.FileFormat
2023-08-16 22:27:31     at net.sourceforge.plantuml.servlet.MapServlet.getOutputFormat(MapServlet.java:70)
2023-08-16 22:27:31     at net.sourceforge.plantuml.servlet.MapServlet.doGet(MapServlet.java:55)
2023-08-16 22:27:31     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:500)
2023-08-16 22:27:31     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
2023-08-16 22:27:31     at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
2023-08-16 22:27:31     at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
2023-08-16 22:27:31     at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
2023-08-16 22:27:31     at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
2023-08-16 22:27:31     at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
2023-08-16 22:27:31     at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
2023-08-16 22:27:31     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
2023-08-16 22:27:31     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
2023-08-16 22:27:31     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
2023-08-16 22:27:31     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
2023-08-16 22:27:31     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
2023-08-16 22:27:31     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
2023-08-16 22:27:31     at org.eclipse.jetty.server.Server.handle(Server.java:563)
2023-08-16 22:27:31     at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
2023-08-16 22:27:31     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
2023-08-16 22:27:31     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
2023-08-16 22:27:31     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
2023-08-16 22:27:31     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
2023-08-16 22:27:31     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
2023-08-16 22:27:31     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
2023-08-16 22:27:31     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
2023-08-16 22:27:31     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
2023-08-16 22:27:31     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
2023-08-16 22:27:31     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
2023-08-16 22:27:31     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
2023-08-16 22:27:31     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
2023-08-16 22:27:31     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
2023-08-16 22:27:31     at java.base/java.lang.Thread.run(Unknown Source)
```

</p>
</details>

### PR DESCRIPTION
**Pull request by HeinrichAD**
This issue should prevent X11 errors in Windows 11 like e.g. issue #311 by forcing the PlantUML server to run `java.awt` to run in headless mode.

closes #311

### CODE REVIEW

File: src/main/java/net/sourceforge/plantuml/servlet/DiagramResponse.java [hunk 1]
```diff
@@ -121,6 +121,10 @@ public static void init() {
             return;
         }
         initialized = true;
+        // set headless mode manually since otherwise Windows 11 seems to have some issues with it
+        // see Issue#311 :: https://github.com/plantuml/plantuml-server/issues/311
+        // NOTE: This can only be set before any awt/X11/... related stuff is loaded
+        System.setProperty("java.awt.headless", "true");
```
Comment (HeinrichAD) [inline src/main/java/net/sourceforge/plantuml/servlet/DiagramResponse.java:127]: An alternatve would be not to force it but only set it by default:
```java
System.setProperty("java.awt.headless", System.getProperty("java.awt.headless", "true"));
```

Maybe that would be a better solution? Should I change that?
The only way to force the PlantUML server to **not** run headless mode (for whatever reason) would now be to use the environment variable `PLANTUML_PROPERTY_FILE` like in this example : https://github.com/plantuml/plantuml-server/issues/311#issuecomment-1703229440

**Comment by HeinrichAD** [comment]
@The-Lum you seem to have followed the ticket. Could I ask you for your opinion?

**Comment by The-Lum** [comment]
Hi,

I have only followed from afar, and I am not much more value on this subject. Sorry for that.
But if that resolves the issue. That's ok.

Regards,
Th.

**Comment by HeinrichAD** [comment]
Ah. OK. Thanks. I am a little unhappy with it and undecided. I will see what I think about it tomorrow and change or merge it than. 😅

**Comment by The-Lum** [comment]
Ask perhaps also @arnaudroques?

_May the night bring advice..._

File: src/main/java/net/sourceforge/plantuml/servlet/DiagramResponse.java (hunk 1 above)
Comment (HeinrichAD) [reply src/main/java/net/sourceforge/plantuml/servlet/DiagramResponse.java]: I decided not to force the server to run in headless mode and still respect the users decision and only set the default/fallback to be `true` (headless mode). If the error still remains we can still adjust it.
